# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RXLabz.logs
email: erick@rxlabz.com
description: > # this means to ignore newlines until "baseurl:"
  Notes et autres bidouilles - Swift, Angular2, React, JS, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rxlabz.github.io" # the base hostname & protocol for your site
twitter_username: rxlabz
github_username:  rxlabz

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

#options
comments: true
provider : disqus
disqus :
    short_name : rxlabzlogs

gems:
  - jemoji